name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test_and_run:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.11
      uses: actions/setup-python@v4.7.0
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        sudo apt update -y
        sudo apt install -y poppler-utils
        sudo apt install tesseract-ocr-pol -y


    - name: Test with pytest
      run: |
        pytest
      
    - name: Run with python
      run: |
        uvicorn pdf_reader.main:app --workers 1 --host 0.0.0.0 --port 8081
      env:
        BOOTSTRAP_SERVERS: localhost:9092
        PDF_TEXT_TOPIC: pdf-text


  docker_build_and_push:

    runs-on: ubuntu-latest

    needs: ["test_and_run"]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2.9.1

    - name: Login to Docker Registry
      uses: docker/login-action@v2.2.0
      with:
        registry: https://cvizard.com:5001
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v4.1.1
      with:
        context: .
        push: true
        tags: cvizard.com:5001/pdfreader:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
           
  deploy:

      runs-on: ubuntu-latest

      needs: ["docker_build_and_push"]
      
      steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: install ssh
        run: sudo apt-get install -y ssh
        
      - name: Login to Docker Registry
        uses: docker/login-action@v2.2.0
        with:
          registry: https://cvizard.com:5001
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker login cvizard.com:5001 -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            sed -i 's|cvizard.com:5001/pdfreader:.*|cvizard.com:5001/pdfreader:${{ github.sha }}|' CVizard/docker-compose.yml
            cd CVizard && docker compose stop pdfreader && docker compose build pdfreader && docker compose up -d pdfreader


