name: Test and Run

on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test_and_run:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.11
      uses: actions/setup-python@v4.7.0
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        sudo apt update -y
        sudo apt install -y poppler-utils
        sudo apt install tesseract-ocr-pol -y


    - name: Test with pytest
      run: |
        pytest
      
    - name: Run uvicorn
      run: |
        uvicorn pdf_reader.main:app --workers 1 --host 0.0.0.0 --port 8081 &
        echo $! > uvicorn_pid.txt &
        sleep 5 &
        kill -9 `cat uvicorn_pid.txt` &
        rm uvicorn_pid.txt &
      env:
        BOOTSTRAP_SERVERS: localhost:9092
        PDF_TEXT_TOPIC: pdf-text